### ISSUE TITLE
SWIG < 3.0

### ISSUE THREAD

**Issue by moorepants** [conda-forge/swig-feedstock#10]
I'm working on a package that requires SWIG to be version 2. Is there a suggested way to make a recipe for version 2 so that those binaries would be available on the conda-forge channel? Do I send a PR here or should I make a new feedstock at staged-recipes.

**Comment by jakirkham** [comment]
We can add a branch for it and then you can submit a PR against it. In the interim, you can submit the PR against `master` and we can redirect it later.

Is this something that we need to be maintaining? Does it matter what version of 2? Could it just be 2 latest?

**Comment by jschueller** [comment]
what package ?

**Comment by moorepants** [comment]
The latest version of 2 is fine.

**Comment by moorepants** [comment]
The package I'm working on is opensim: https://github.com/conda-forge/staged-recipes/pull/2136

**Comment by jakirkham** [comment]
Ok, please put together a PR against `master` for now. Once it is ready we will add a `2` branch and retarget the PR against that branch. Also please add yourself as a maintainer.

**Comment by moorepants** [comment]
Ok, it may be a couple weeks until I can get back to this. Thanks.

**Comment by jschueller** [comment]
seems opensim requires swig>=3.0.8 now, closing

**Comment by moorepants** [comment]
This was relevant to OpenSim 3 not 4. But I do not plan to proceed, nonetheless.
